language: julia
sudo: false
os:
  - linux
#  - osx

# TODO: Replace with 0.7 once released
julia:
 - nightly

notifications:
  email: false
  
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("IPNets"); Pkg.test("IPNets"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("IPNets")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
